# Generated by Django 5.2.3 on 2025-06-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("age", models.IntegerField(help_text="Age in months")),
                (
                    "weight",
                    models.FloatField(help_text="Average weight per animal in kg"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_type", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("purchase_date", models.DateField()),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicationDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.FloatField()),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.breed",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.feedtype",
                    ),
                ),
            ],
        ),
    ]
